name: CD

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set environment for version
        run: long="${{ github.ref }}"; version=${long#"refs/tags/v"}; echo "version=${version}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish
        run: ./gradlew -Pversion=$version publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
