name: CD

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish
        run: ./gradlew publishToMavenLocal
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          path: ~/.m2
